config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friend_requests, only: [:index, :create, :destroy]
  
  get    '/home',        to: 'static_pages#home'
  post   '/friendships', to: 'friendships#create'
  delete '/friendships', to: 'friendships#destroy'
  
  root 'static_pages#home'
  
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
	belongs_to :from_user, class_name: "User"
	belongs_to :to_user, class_name: "User"

	def self.cleanup(first_id, second_id)
		request_one = FriendRequest.where("from_user_id = ? AND to_user_id = ?",
							second_id, first_id)[0]
		request_one.destroy if request_one

		request_two = FriendRequest.where("from_user_id = ? AND to_user_id = ?",
							first_id, second_id)[0]
		request_two.destroy if request_two
	end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :require_log_in
  
  def index
  	@friend_requests = FriendRequest.where(to_user_id: current_user.id)
  	#ids = current_user.friend_requests.map(&:to_user_id)
  	#@users_requested = User.where("id IN (?)", ids)
  end

  def create
  	f = current_user.friend_requests.create!(to_user_id: params[:to_user_id])
  	redirect_to request.referrer || users_path
  end

  def destroy
    @friend_request = FriendRequest.find(params[:id])
    @friend_request.destroy
    redirect_to request.referrer || friend_requests_path
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_accept_form.html.erb
<%= form_with(url: friendships_path, local: true) do |f| %>

  <%= f.submit "accepter" %>
<% end %>

app/views/friend_requests/_delete_form.html.erb
<%= form_with(model: FriendRequest.find(request_id), local: true, method: :delete) do |f| %>
  <%# hidden_field_tag :request_id, request_id %>
  <%= f.submit "effacer" %>
<% end %>

app/views/friend_requests/_friend_request.html.erb
<div class="friend_request">
	<% user = friend_request.from_user %>
	<%= link_to user.name, user_path(user) %>
	<%= link_to 'accepter', friendships_path(user_id: user.id), method: 'post' %>
	<%# link_to 'effacer', %>
	<%# render partial: 'friend_requests/accept_form', locals: { request_id: friend_request.id } %>
	<%= render partial: 'friend_requests/delete_form', locals: { request_id: friend_request.id } %>
	recu <%= friend_request.created_at.strftime("%b %d a %I:%M") %>
</div>

app/views/friend_requests/_friend_request_form.html.erb
<%= form_with(model: current_user.friend_requests.build, local: true) do |f| %>
  <%= hidden_field_tag :to_user_id, to_user_id %>
  <%= f.submit "friend +1" %>
<% end %>

app/views/friend_requests/index.html.erb
<h1>Vos Demandes D'Ami</h1>
<% if @friend_requests.empty? %>
  aucune demande maintenant :/
<% else %>
  <%= render @friend_requests, locals: {besoin: "tais-toi"} %>
<% end %>