config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friend_requests, only: [:index, :create, :destroy]
  
  get    '/home',        to: 'static_pages#home'
  post   '/friendships', to: 'friendships#create'
  delete '/friendships', to: 'friendships#destroy'
  
  root 'static_pages#home'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: :true, length: { maximum: 100 }
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
	belongs_to :from_user, class_name: "User"
	belongs_to :to_user, class_name: "User"

	def self.cleanup(first_id, second_id)
		request_one = FriendRequest.where("from_user_id = ? AND to_user_id = ?",
							second_id, first_id)[0]
		request_one.destroy if request_one

		request_two = FriendRequest.where("from_user_id = ? AND to_user_id = ?",
							first_id, second_id)[0]
		request_two.destroy if request_two
	end
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :liker, class_name: "User"
	belongs_to :liked_post, class_name: "Post"
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :comments
  has_many :likes, foreign_key: :liked_post_id
  has_many :likers, through: :likes

  validates :content, presence: true, length: { maximum: 1000 }
  
  def display_image
  	image.variant(resize_to_limit: [500,500])
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_picture

  has_many :posts
  has_many :photo_posts
  has_many :comments
  has_many :likes, foreign_key: :liker_id
  has_many :liked_posts, through: :likes
  has_and_belongs_to_many :friends,
  						  class_name: "User",
  						  join_table: :friendships,
  						  foreign_key: :user_id,
  						  association_foreign_key: :friend_user_id
  has_many :friend_requests, foreign_key: :from_user_id
  has_many :received_requests, through: :friend_requests, source: :to_user
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: %i[facebook]

  validates :profile_picture, content_type: { in: %w[image/jpeg image/gif image/png],
                                              message: "must be valid image format" },
                              size: { less_than: 5.megabytes,
                                      message: "should be less than 5 MB" }

  after_create :send_sign_up_email

  def feed
    my_id = id
    id_list = friend_ids
    id_list << my_id
    Post.where("user_id IN (#{id_list.join(', ')})").order(created_at: :desc)
  end

  def like(post)
    self.likes.create!(liked_post_id: post.id)
  end

  def unlike(post)
    self.likes.find_by(liked_post_id: post.id).destroy
  end

  def request_sent?(to_user_id)
    if FriendRequest.where("from_user_id = ? AND to_user_id = ?",
                id, to_user_id ).empty?
      return false
    end
    true
  end

  def received_requests_count
    FriendRequest.where(to_user_id: id).count
  end

  def friend(other_user)
    self.friends << other_user
    other_user.friends << self
  end

  def display_profile_picture
    if profile_picture.attached?
      profile_picture.variant(resize_to_limit: [200,200])
    else
      "default.jpg"
    end
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      #user.profile_picture = auth.info.image
    end
  end

  def send_sign_up_email
    UserMailer.sign_up_email(self).deliver_now!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# info about storing location and redirecting
	# after sign in:
	# https://github.com/heartcombo/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update

	include ApplicationHelper
	before_action :store_user_location!, if: :storable_location?
	#before_action :require_log_in, except: [:new, :create]
	#before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	private

	  def configure_permitted_parameters
	  	update_attrs = [:name, :password, :password_confirmation, :current_password, :profile_picture]
	  	devise_parameter_sanitizer.permit(:sign_up, keys: update_attrs)
	  	devise_parameter_sanitizer.permit(:account_update, keys: update_attrs)
	  end

	  def storable_location?
	  	request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
	  end

	  def store_user_location!
	  	store_location_for(:user, request.fullpath)
	  end

	  def after_sign_in_path_for(resource_or_scope)
		stored_location_for(resource_or_scope) || super
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :correct_user, only: [:destroy]

	def create
		@comment = current_user.comments.build(comment_params)
		if @comment.save
			redirect_to params[:current_url]
		else
			render :new
		end
	end

	def edit
	end

	def update
	end

	def destroy
		@comment.destroy
		flash[:success] = "commentaire effacer"
		redirect_to request.referrer || home_path
	end

	private

		def comment_params
			params.require(:comment).permit(:content, :post_id)
		end

		def correct_user
			@comment = current_user.comments.find_by(id: params[:id])
			if @comment.nil?
				redirect_to request.referrer || home_path
			end
		end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :require_log_in

	def create
		post = Post.find(params[:liked_post_id])
		current_user.like(post)
		redirect_to params[:current_url]
	end

	def destroy
		post = Post.find(params[:liked_post_id])
		current_user.unlike(post)
		redirect_to params[:current_url]
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :require_log_in

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post cree"
			redirect_to root_url
		else
			@feed_items = current_user.feed
			render 'static_pages/home'
		end
	end

	def destroy
	end

	private

	  def post_params
	  	params.require(:post).permit(:content, :image)
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_log_in
    
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@feed_items = @user.feed
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def require_log_in
	  	if !user_signed_in?
	  		puts "NOT SIGNED IN"
	  		redirect_to new_user_session_path
	  	end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photo_posts_helper.rb
module PhotoPostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div id="user_nav">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>
        <%= link_to "Deconnexion", destroy_user_session_path, method: :delete %>
        <%= link_to "Mon profil", user_path(current_user) %>
        <%= link_to "l'accueil", home_path %>
        <%= link_to "tous le monde", users_path %>
        <%= link_to "demande d'ami(#{current_user.received_requests_count})", friend_requests_path %>
      <% else %>
        <%= link_to "S'inscrire", new_user_registration_path %> or 
        <%= link_to "Se connecter", new_user_session_path %>
        or <%= link_to "connectez-vous avec facebook",user_facebook_omniauth_authorize_path %>
      <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash">
      <% flash.each do |msg_type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
      <% end %>
    </p>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  	<div class="alert alert-danger">
  		The form contains <%= pluralize(object.errors.count, "error") %>
  	</div>
  	<ul>
  		<% object.errors.full_messages.each do |msg| %>
  		  <li><%= msg %></li>
  		<% end %>
  	</ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true, class: "post_form") do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <br>
  <%= f.label :content, "Vos pensees" %>
  <%= f.text_area :content %>
  <br>
  <%= f.submit "Partager" %>
  <span>
  	<%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>
  </span>
<% end %>